/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 *
 * Generated by: scripts/generate-routes.ts
 * Run: pnpm generate:routes
 */

// Query string builder utility
export function buildQueryString<T extends Record<string, string | number | boolean | undefined>>(
  params?: T
): string {
  if (!params) return ''

  const entries = Object.entries(params).filter(
    ([_, value]) => value !== undefined && value !== ''
  )

  if (entries.length === 0) return ''

  const queryString = entries
    .map(([key, value]) => `${encodeURIComponent(key)}=${encodeURIComponent(String(value))}`)
    .join('&')

  return `?${queryString}`
}

// Type-safe route builders
export const routes = {
  $root: () => '/',
  categories: () => '/categories',
  login: () => '/login',
  vendors: {
    $root: () => '/vendors',
    new: () => '/vendors/new',
    $id: (id: string) => ({
      edit: () => `/vendors/${id}/edit`,
    }),
  },
} as const

// Export type for external usage
export type Routes = typeof routes
